# Meaning of Google Translate query params
#https://stackoverflow.com/questions/26714426/what-is-the-meaning-of-google-translate-query-params/29537590#29537590
[Audio]
###
https://translate.google.com/translate_tts?client=tw-ob&q=ordnance&tl=en

###
https://translate.google.com/translate_tts?ie=UTF-8&q=brittle&tl=en&total=1&idx=0&textlen=7&client=dict-chrome-ex&prev=input&ttsspeed=0.5

[Text]
###
https://translate.googleapis.com/translate_a/single?client=gtx&sl=${sourceLang}&tl=${targetLang}&dt=t&dt=bd&dj=1&q=${query}
###

https://translate.googleapis.com/translate_a/single
?dt=t
&client=gtx
&dt=bd
&dt=qc
&dt=rm
&dt=ld
&dt=md
&dt=ss
&dt=rw
&dt=sw
&dj=1
&hl=en
&sl=auto
&tl=ru
&tk=727849.727849
&q=fast