export const supportedLanguages = [
  { code: "auto", name: "Automatic", country_code: "AQ" },
  { code: "af", name: "Afrikaans", country_code: "ZA" },
  { code: "sq", name: "Albanian", country_code: "AL" },
  { code: "am", name: "Amharic", country_code: "ET" },
  { code: "ar", name: "Arabic", country_code: "AQ" }, // REVISIT
  { code: "hy", name: "Armenian", country_code: "AM" },
  { code: "az", name: "Azerbaijani", country_code: "AZ" },
  { code: "eu", name: "Basque", country_code: "AQ" }, // REVISIT
  { code: "be", name: "Belarusian", country_code: "BY" },
  { code: "bn", name: "Bengali", country_code: "BD" },
  { code: "bs", name: "Bosnian", country_code: "BA" },
  { code: "bg", name: "Bulgarian", country_code: "BG" },
  { code: "ca", name: "Catalan", country_code: "AD" },
  { code: "ceb", name: "Cebuano", country_code: "PH" },
  { code: "ny", name: "Chichewa", country_code: "MW" },
  { code: "zh-CN", name: "Chinese (Simplified)", country_code: "CN" },
  { code: "zh-TW", name: "Chinese (Traditional)", country_code: "CN" },
  { code: "co", name: "Corsican", country_code: "FR" },
  { code: "hr", name: "Croatian", country_code: "HR" },
  { code: "cs", name: "Czech", country_code: "CZ" },
  { code: "da", name: "Danish", country_code: "DK" },
  { code: "nl", name: "Dutch", country_code: "NL" },
  { code: "en", name: "English", country_code: "GB-UKM" },
  { code: "eo", name: "Esperanto", country_code: "AQ" }, // REVISIT
  { code: "et", name: "Estonian", country_code: "EE" },
  { code: "tl", name: "Filipino", country_code: "PH" },
  { code: "fi", name: "Finnish", country_code: "FI" },
  { code: "fr", name: "French", country_code: "FR" },
  { code: "fy", name: "Frisian", country_code: "NL" }, // REVISIT NL/DE
  { code: "gl", name: "Galician", country_code: "AQ" }, // REVISIT SPAIN
  { code: "ka", name: "Georgian", country_code: "GE" },
  { code: "de", name: "German", country_code: "DE" },
  { code: "el", name: "Greek", country_code: "GR" },
  { code: "gu", name: "Gujarati", country_code: "IN" },
  { code: "ht", name: "Haitian Creole", country_code: "HT" },
  { code: "ha", name: "Hausa", country_code: "NG" },
  { code: "haw", name: "Hawaiian", country_code: "AQ" }, // REVISIT
  { code: "iw", name: "Hebrew", country_code: "IL" },
  { code: "hi", name: "Hindi", country_code: "IN" },
  { code: "hmn", name: "Hmong", country_code: "CN" },
  { code: "hu", name: "Hungarian", country_code: "HU" },
  { code: "is", name: "Icelandic", country_code: "IS" },
  { code: "ig", name: "Igbo", country_code: "NG" },
  { code: "id", name: "Indonesian", country_code: "ID" },
  { code: "ga", name: "Irish", country_code: "IE" },
  { code: "it", name: "Italian", country_code: "IT" },
  { code: "ja", name: "Japanese", country_code: "JP" },
  { code: "jw", name: "Javanese", country_code: "JV" }, // REVISIT JAVA
  { code: "kn", name: "Kannada", country_code: "IN" },
  { code: "kk", name: "Kazakh", country_code: "KZ" },
  { code: "km", name: "Khmer", country_code: "KH" },
  { code: "rw", name: "Kinyarwanda", country_code: "RW" },
  { code: "ko", name: "Korean", country_code: "KR" },
  { code: "ku", name: "Kurdish (Kurmanji)", country_code: "AQ" }, // REVISIT
  { code: "ky", name: "Kyrgyz", country_code: "KG" },
  { code: "lo", name: "Lao", country_code: "LA" },
  { code: "la", name: "Latin", country_code: "VA" },
  { code: "lv", name: "Latvian", country_code: "LV" },
  { code: "lt", name: "Lithuanian", country_code: "LT" },
  { code: "lb", name: "Luxembourgish", country_code: "LU" },
  { code: "mk", name: "Macedonian", country_code: "MK" },
  { code: "mg", name: "Malagasy", country_code: "MG" },
  { code: "ms", name: "Malay", country_code: "MY" },
  { code: "ml", name: "Malayalam", country_code: "HI" },
  { code: "mt", name: "Maltese", country_code: "MT" },
  { code: "mi", name: "Maori", country_code: "NZ" },
  { code: "mr", name: "Marathi", country_code: "HI" },
  { code: "mn", name: "Mongolian", country_code: "MN" },
  { code: "my", name: "Myanmar (Burmese)", country_code: "MM" },
  { code: "ne", name: "Nepali", country_code: "NP" },
  { code: "no", name: "Norwegian", country_code: "NO" },
  { code: "or", name: "Odia (Oriya)", country_code: "HI" },
  { code: "ps", name: "Pashto", country_code: "AF" },
  { code: "fa", name: "Persian", country_code: "IR" },
  { code: "pl", name: "Polish", country_code: "PL" },
  { code: "pt", name: "Portuguese", country_code: "PT" },
  { code: "pa", name: "Punjabi", country_code: "HI" },
  { code: "ro", name: "Romanian", country_code: "RO" },
  { code: "ru", name: "Russian", country_code: "RU" },
  { code: "sm", name: "Samoan", country_code: "WS" },
  { code: "gd", name: "Scots Gaelic", country_code: "GB-SCT" },
  { code: "sr", name: "Serbian", country_code: "RS" },
  { code: "st", name: "Sesotho", country_code: "LS" },
  { code: "sn", name: "Shona", country_code: "ZW" },
  { code: "sd", name: "Sindhi", country_code: "PK" },
  { code: "si", name: "Sinhala", country_code: "LK" },
  { code: "sk", name: "Slovak", country_code: "SK" },
  { code: "sl", name: "Slovenian", country_code: "SI" },
  { code: "so", name: "Somali", country_code: "SO" },
  { code: "es", name: "Spanish", country_code: "ES" },
  { code: "su", name: "Sundanese", country_code: "AQ" }, // REVISIT JAVA
  { code: "sw", name: "Swahili", country_code: "TZ" },
  { code: "sv", name: "Swedish", country_code: "SE" },
  { code: "tg", name: "Tajik", country_code: "TJ" },
  { code: "ta", name: "Tamil", country_code: "HI" },
  { code: "tt", name: "Tatar", country_code: "AQ" }, // REVISIT
  { code: "te", name: "Telugu", country_code: "HI" },
  { code: "th", name: "Thai", country_code: "TH" },
  { code: "tr", name: "Turkish", country_code: "TR" },
  { code: "tk", name: "Turkmen", country_code: "TM" },
  { code: "uk", name: "Ukrainian", country_code: "UA" },
  { code: "ur", name: "Urdu", country_code: "PK" },
  { code: "ug", name: "Uyghur", country_code: "CN" }, // REVISIT
  { code: "uz", name: "Uzbek", country_code: "UZ" },
  { code: "vi", name: "Vietnamese", country_code: "VN" },
  { code: "cy", name: "Welsh", country_code: "GB-WLS" },
  { code: "xh", name: "Xhosa", country_code: "ZA" },
  { code: "yi", name: "Yiddish", country_code: "IL" },
  { code: "yo", name: "Yoruba", country_code: "NG" },
  { code: "zu", name: "Zulu", country_code: "ZA" },
] as const;
